/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.sistemanossolar.view;

/**
 *
 * @author AFSOUZA
 */
public class BuscarPessoa extends javax.swing.JDialog {

    /**
     * Creates new form BuscarPessoa
     */
    public BuscarPessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBuscarPessoa = new javax.swing.JPanel();
        pnBuscarPessoaFiltros = new javax.swing.JPanel();
        lbBuscarPessoaNome = new javax.swing.JLabel();
        tfBuscarPessoaNome = new javax.swing.JTextField();
        lbBuscarPessoaTipo = new javax.swing.JLabel();
        cbBuscarPessoaTipo = new javax.swing.JComboBox<>();
        lbBuscarPessoaCidade = new javax.swing.JLabel();
        cbBuscarPessoaCidade = new javax.swing.JComboBox<>();
        btBuscarPessoaBuscar = new javax.swing.JButton();
        pnBuscarPessoaResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscarPessoa = new javax.swing.JTable();
        btBuscarPessoaSelecionar = new javax.swing.JButton();
        btBuscarPessoaNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnBuscarPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar [TIPO PESSOA]"));

        pnBuscarPessoaFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        lbBuscarPessoaNome.setText("Nome:");

        tfBuscarPessoaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarPessoaNomeActionPerformed(evt);
            }
        });
        tfBuscarPessoaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarPessoaNomeKeyTyped(evt);
            }
        });

        lbBuscarPessoaTipo.setText("Tipo");
        lbBuscarPessoaTipo.setToolTipText("");

        cbBuscarPessoaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beneficiário", "Assistente", "Doador" }));

        lbBuscarPessoaCidade.setText("Cidade");
        lbBuscarPessoaCidade.setToolTipText("");

        cbBuscarPessoaCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Ituiutaba-MG", "Paracatu-MG" }));

        btBuscarPessoaBuscar.setText("Buscar");
        btBuscarPessoaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPessoaBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarPessoaFiltrosLayout = new javax.swing.GroupLayout(pnBuscarPessoaFiltros);
        pnBuscarPessoaFiltros.setLayout(pnBuscarPessoaFiltrosLayout);
        pnBuscarPessoaFiltrosLayout.setHorizontalGroup(
            pnBuscarPessoaFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarPessoaFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPessoaNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfBuscarPessoaNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarPessoaFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarPessoaFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPessoaTipo)
                        .addGap(69, 69, 69))
                    .addComponent(cbBuscarPessoaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarPessoaFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarPessoaCidade)
                    .addGroup(pnBuscarPessoaFiltrosLayout.createSequentialGroup()
                        .addComponent(cbBuscarPessoaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscarPessoaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnBuscarPessoaFiltrosLayout.setVerticalGroup(
            pnBuscarPessoaFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnBuscarPessoaFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPessoaNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBuscarPessoaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBuscarPessoaFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPessoaTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBuscarPessoaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBuscarPessoaFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPessoaCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBuscarPessoaFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBuscarPessoaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscarPessoaBuscar))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnBuscarPessoaResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        tableBuscarPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód.", "Nome", "Cidade", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBuscarPessoa);

        javax.swing.GroupLayout pnBuscarPessoaResultadoLayout = new javax.swing.GroupLayout(pnBuscarPessoaResultado);
        pnBuscarPessoaResultado.setLayout(pnBuscarPessoaResultadoLayout);
        pnBuscarPessoaResultadoLayout.setHorizontalGroup(
            pnBuscarPessoaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnBuscarPessoaResultadoLayout.setVerticalGroup(
            pnBuscarPessoaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        btBuscarPessoaSelecionar.setText("Selecionar");

        btBuscarPessoaNovo.setText("Novo");

        javax.swing.GroupLayout pnBuscarPessoaLayout = new javax.swing.GroupLayout(pnBuscarPessoa);
        pnBuscarPessoa.setLayout(pnBuscarPessoaLayout);
        pnBuscarPessoaLayout.setHorizontalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                        .addComponent(btBuscarPessoaSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarPessoaNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                        .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnBuscarPessoaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnBuscarPessoaFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        pnBuscarPessoaLayout.setVerticalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoaFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBuscarPessoaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBuscarPessoaSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btBuscarPessoaNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarPessoaNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarPessoaNomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPessoaNomeKeyTyped

    private void tfBuscarPessoaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarPessoaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPessoaNomeActionPerformed

    private void btBuscarPessoaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPessoaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarPessoaBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarPessoa dialog = new BuscarPessoa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarPessoaBuscar;
    private javax.swing.JButton btBuscarPessoaNovo;
    private javax.swing.JButton btBuscarPessoaSelecionar;
    private javax.swing.JComboBox<String> cbBuscarPessoaCidade;
    private javax.swing.JComboBox<String> cbBuscarPessoaTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarPessoaCidade;
    private javax.swing.JLabel lbBuscarPessoaNome;
    private javax.swing.JLabel lbBuscarPessoaTipo;
    private javax.swing.JPanel pnBuscarPessoa;
    private javax.swing.JPanel pnBuscarPessoaFiltros;
    private javax.swing.JPanel pnBuscarPessoaResultado;
    private javax.swing.JTable tableBuscarPessoa;
    private javax.swing.JTextField tfBuscarPessoaNome;
    // End of variables declaration//GEN-END:variables
}
