/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.sistemanossolar.view;

import br.edu.iftm.sistemanossolar.controller.doacao.DoacaoController;
import br.edu.iftm.sistemanossolar.model.doacao.Doacao;
import br.edu.iftm.sistemanossolar.model.doacao.Produto;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AFSOUZA
 */
public class BuscarDoacao extends javax.swing.JDialog {
    private static Telas tela;
    private static DoacaoController doacaoController;
    private Doacao doacao;
    private List<Doacao> listagem = new ArrayList<>();
    private DefaultTableModel modelo;
    private List<Produto> produtos;
    /**
     * Creates new form BuscarPessoa
     */
    public BuscarDoacao(java.awt.Frame parent, boolean modal, Connection conexao, Telas tela) {
        super(parent, modal);
        doacaoController = new DoacaoController(conexao);
        initComponents();
        this.tela = tela;
        modelo = (DefaultTableModel) tableBuscarPessoa.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBuscarPessoa = new javax.swing.JPanel();
        pnBuscarDoacaoFiltros = new javax.swing.JPanel();
        lbBuscarDoacaoDoador = new javax.swing.JLabel();
        tfBuscarDoacaoDoador = new javax.swing.JTextField();
        lbBuscarDoacaoTipo = new javax.swing.JLabel();
        cbBuscarDocaoTipo = new javax.swing.JComboBox<>();
        lbBuscarDoacaoData1 = new javax.swing.JLabel();
        ffBuscarDoacaoDataInicio = new javax.swing.JFormattedTextField();
        lbBuscarDoacaoData2 = new javax.swing.JLabel();
        ffBuscarDoacaoDataFim = new javax.swing.JFormattedTextField();
        btBuscarDoacao = new javax.swing.JButton();
        pnBuscarDoacaoResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscarPessoa = new javax.swing.JTable();
        btBuscarDoacaoSair = new javax.swing.JButton();
        btBuscarDoacaoLimpar = new javax.swing.JButton();
        btBuscarDoacaoSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnBuscarPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Doação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        pnBuscarDoacaoFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lbBuscarDoacaoDoador.setText("Doador:");
        lbBuscarDoacaoDoador.setToolTipText("");

        tfBuscarDoacaoDoador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBuscarDoacaoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarDoacaoDoadorActionPerformed(evt);
            }
        });
        tfBuscarDoacaoDoador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarDoacaoDoadorKeyTyped(evt);
            }
        });

        lbBuscarDoacaoTipo.setText("Tipo:");
        lbBuscarDoacaoTipo.setToolTipText("");

        cbBuscarDocaoTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbBuscarDocaoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Dinheiro", "Produto" }));

        lbBuscarDoacaoData1.setText("Data Inicio:");
        lbBuscarDoacaoData1.setToolTipText("");

        try {
            ffBuscarDoacaoDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ffBuscarDoacaoDataInicio.setText("");
        ffBuscarDoacaoDataInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbBuscarDoacaoData2.setText("Data Fim:");
        lbBuscarDoacaoData2.setToolTipText("");

        try {
            ffBuscarDoacaoDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ffBuscarDoacaoDataFim.setText("");
        ffBuscarDoacaoDataFim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btBuscarDoacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        btBuscarDoacao.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btBuscarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarDoacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarDoacaoFiltrosLayout = new javax.swing.GroupLayout(pnBuscarDoacaoFiltros);
        pnBuscarDoacaoFiltros.setLayout(pnBuscarDoacaoFiltrosLayout);
        pnBuscarDoacaoFiltrosLayout.setHorizontalGroup(
            pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarDoacaoDoador)
                    .addComponent(tfBuscarDoacaoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarDoacaoTipo)
                    .addComponent(cbBuscarDocaoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarDoacaoData1)
                    .addComponent(ffBuscarDoacaoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarDoacaoData2)
                    .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                        .addComponent(ffBuscarDoacaoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscarDoacao)))
                .addGap(10, 10, 10))
        );
        pnBuscarDoacaoFiltrosLayout.setVerticalGroup(
            pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfBuscarDoacaoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                                .addComponent(lbBuscarDoacaoData2)
                                .addGap(10, 10, 10)
                                .addComponent(btBuscarDoacao))
                            .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                                .addComponent(lbBuscarDoacaoData1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ffBuscarDoacaoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ffBuscarDoacaoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                            .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbBuscarDoacaoTipo)
                                .addComponent(lbBuscarDoacaoDoador))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbBuscarDocaoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnBuscarDoacaoResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        pnBuscarDoacaoResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tableBuscarPessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableBuscarPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Doador", "Tipo", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBuscarPessoa);

        javax.swing.GroupLayout pnBuscarDoacaoResultadoLayout = new javax.swing.GroupLayout(pnBuscarDoacaoResultado);
        pnBuscarDoacaoResultado.setLayout(pnBuscarDoacaoResultadoLayout);
        pnBuscarDoacaoResultadoLayout.setHorizontalGroup(
            pnBuscarDoacaoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarDoacaoResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnBuscarDoacaoResultadoLayout.setVerticalGroup(
            pnBuscarDoacaoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarDoacaoResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnBuscarPessoaLayout = new javax.swing.GroupLayout(pnBuscarPessoa);
        pnBuscarPessoa.setLayout(pnBuscarPessoaLayout);
        pnBuscarPessoaLayout.setHorizontalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnBuscarDoacaoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBuscarDoacaoFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnBuscarPessoaLayout.setVerticalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarDoacaoFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBuscarDoacaoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBuscarDoacaoSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarDoacaoSair.setText("Sair");
        btBuscarDoacaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarDoacaoSairActionPerformed(evt);
            }
        });

        btBuscarDoacaoLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarDoacaoLimpar.setText("Limpar");
        btBuscarDoacaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarDoacaoLimparActionPerformed(evt);
            }
        });

        btBuscarDoacaoSelecionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarDoacaoSelecionar.setText("Selecionar");
        btBuscarDoacaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarDoacaoSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btBuscarDoacaoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarDoacaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarDoacaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscarDoacaoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarDoacaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarDoacaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarDoacaoActionPerformed
        String nomeDoador = tfBuscarDoacaoDoador.getText();
        String tipoDoacao = (String) cbBuscarDocaoTipo.getSelectedItem();
        
        String campoDataInicio = ffBuscarDoacaoDataInicio.getText().trim();
        String campoDataFim = ffBuscarDoacaoDataFim.getText().trim();
        DateTimeFormatter dataFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataInicio;
        if(campoDataInicio.contains(" ") || campoDataInicio.equals("//")){
            dataInicio = null;
        }else{
            dataInicio = LocalDate.parse(campoDataInicio, dataFormat);
        }
        LocalDate dataFim;
        if(campoDataFim.contains(" ") || campoDataFim.equals("//")){
            dataFim = null;
        }else{
            dataFim = LocalDate.parse(campoDataFim, dataFormat);
        }
        try{
            listagem = doacaoController.listarDoacoes(nomeDoador, tipoDoacao, dataInicio, dataFim);
        }catch (SQLException e){
            e.printStackTrace();
        }
        alimentaTabela(listagem);
    }//GEN-LAST:event_btBuscarDoacaoActionPerformed

    private void tfBuscarDoacaoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarDoacaoDoadorActionPerformed
        
    }//GEN-LAST:event_tfBuscarDoacaoDoadorActionPerformed
    
    private void tfBuscarDoacaoDoadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarDoacaoDoadorKeyTyped
        char entrada = evt.getKeyChar();
        if(!Character.isLetter(entrada) && entrada != ' '){
            evt.consume();
        }
    }//GEN-LAST:event_tfBuscarDoacaoDoadorKeyTyped

    private void btBuscarDoacaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarDoacaoLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_btBuscarDoacaoLimparActionPerformed

    public void limparTela(){
        tfBuscarDoacaoDoador.setText("");
        cbBuscarDocaoTipo.setSelectedIndex(0);
        ffBuscarDoacaoDataInicio.setText("");
        ffBuscarDoacaoDataFim.setText("");
        modelo.setRowCount(0);
    }
    
    private void btBuscarDoacaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarDoacaoSelecionarActionPerformed
        if (tableBuscarPessoa.getSelectedRow() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma pessoa!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            int indiceDoacao = tableBuscarPessoa.getSelectedRow();
            doacao = listagem.get(indiceDoacao);
            produtos = doacaoController.listagemDeProduto(doacao);
            doacao.setProduto(produtos);
            tela.preencheDoacao(doacao);
            limparTela();
            dispose();
        }
    }//GEN-LAST:event_btBuscarDoacaoSelecionarActionPerformed

    private void btBuscarDoacaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarDoacaoSairActionPerformed
        limparTela();
        dispose();
    }//GEN-LAST:event_btBuscarDoacaoSairActionPerformed
    
    public void alimentaTabela(List<Doacao> listagem){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        modelo.setRowCount(0);
        for(Doacao doacao : listagem){
            Object[] linha = {doacao.getId(), doacao.getDoador().getNome(), doacao.getTipo(), doacao.getDataDoacao().format(formatter)};
            modelo.addRow(linha);
        }
    }
    
    public Doacao getDoacao(){
        return doacao;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarDoacao;
    private javax.swing.JButton btBuscarDoacaoLimpar;
    private javax.swing.JButton btBuscarDoacaoSair;
    private javax.swing.JButton btBuscarDoacaoSelecionar;
    private javax.swing.JComboBox<String> cbBuscarDocaoTipo;
    private javax.swing.JFormattedTextField ffBuscarDoacaoDataFim;
    private javax.swing.JFormattedTextField ffBuscarDoacaoDataInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarDoacaoData1;
    private javax.swing.JLabel lbBuscarDoacaoData2;
    private javax.swing.JLabel lbBuscarDoacaoDoador;
    private javax.swing.JLabel lbBuscarDoacaoTipo;
    private javax.swing.JPanel pnBuscarDoacaoFiltros;
    private javax.swing.JPanel pnBuscarDoacaoResultado;
    private javax.swing.JPanel pnBuscarPessoa;
    private javax.swing.JTable tableBuscarPessoa;
    private javax.swing.JTextField tfBuscarDoacaoDoador;
    // End of variables declaration//GEN-END:variables
}
