/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.sistemanossolar.view;

import br.edu.iftm.sistemanossolar.controller.PedidoController;
import br.edu.iftm.sistemanossolar.model.pedido.Pedido;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AFSOUZA
 */
public class BuscarPedido extends javax.swing.JDialog {
    
    private PedidoController pedidoController;
    private DefaultTableModel modelo;
    private static Telas tela;
    private List<Pedido> pedidos;

    /**
     * Creates new form BuscarPessoa
     */
    public BuscarPedido(java.awt.Frame parent, boolean modal, Connection conexao, Telas tela) {
        super(parent, modal);
        initComponents();
        pedidoController = new PedidoController(conexao);
        modelo = (DefaultTableModel) tableBuscarPessoa.getModel();
        this.tela = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBuscarPessoa = new javax.swing.JPanel();
        pnBuscarPedidoFiltros = new javax.swing.JPanel();
        lbBuscarPedidoPessoa = new javax.swing.JLabel();
        tfBuscarPedidoPessoa = new javax.swing.JTextField();
        lbBuscarPedidoTipoPessoa = new javax.swing.JLabel();
        cbBuscarPedidoTipoPessoa = new javax.swing.JComboBox<>();
        lbBuscarPedidoData1 = new javax.swing.JLabel();
        ffBuscarPedidoDataInicio = new javax.swing.JFormattedTextField();
        lbBuscarPedidoData2 = new javax.swing.JLabel();
        ffBuscarPedidoDataFim = new javax.swing.JFormattedTextField();
        btBuscarPedido = new javax.swing.JButton();
        pnBuscarPedidoResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscarPessoa = new javax.swing.JTable();
        btBuscarPedidoSelecionar = new javax.swing.JButton();
        btBuscarPedidoLimpar = new javax.swing.JButton();
        btBuscarPedidoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnBuscarPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        pnBuscarPedidoFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lbBuscarPedidoPessoa.setText("Assistente/Beneficiário:");
        lbBuscarPedidoPessoa.setToolTipText("");

        tfBuscarPedidoPessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBuscarPedidoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarPedidoPessoaActionPerformed(evt);
            }
        });
        tfBuscarPedidoPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarPedidoPessoaKeyTyped(evt);
            }
        });

        lbBuscarPedidoTipoPessoa.setText("Tipo:");
        lbBuscarPedidoTipoPessoa.setToolTipText("");

        cbBuscarPedidoTipoPessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbBuscarPedidoTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Assistente", "Beneficiário" }));

        lbBuscarPedidoData1.setText("Data Pedido Inicio:");
        lbBuscarPedidoData1.setToolTipText("");

        try {
            ffBuscarPedidoDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ffBuscarPedidoDataInicio.setText("");
        ffBuscarPedidoDataInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbBuscarPedidoData2.setText("Data Pedido Fim:");
        lbBuscarPedidoData2.setToolTipText("");

        try {
            ffBuscarPedidoDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ffBuscarPedidoDataFim.setText("");
        ffBuscarPedidoDataFim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btBuscarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        btBuscarPedido.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarPedidoFiltrosLayout = new javax.swing.GroupLayout(pnBuscarPedidoFiltros);
        pnBuscarPedidoFiltros.setLayout(pnBuscarPedidoFiltrosLayout);
        pnBuscarPedidoFiltrosLayout.setHorizontalGroup(
            pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBuscarPedidoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBuscarPedidoPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarPedidoTipoPessoa)
                    .addComponent(cbBuscarPedidoTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ffBuscarPedidoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBuscarPedidoData1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addComponent(ffBuscarPedidoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscarPedido))
                    .addComponent(lbBuscarPedidoData2))
                .addGap(10, 10, 10))
        );
        pnBuscarPedidoFiltrosLayout.setVerticalGroup(
            pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPedidoPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBuscarPedidoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBuscarPedidoData1)
                            .addComponent(lbBuscarPedidoData2))
                        .addGap(32, 32, 32))
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPedidoTipoPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ffBuscarPedidoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ffBuscarPedidoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbBuscarPedidoTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btBuscarPedido))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnBuscarPedidoResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tableBuscarPessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableBuscarPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Pessoa", "Tipo", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBuscarPessoa);

        javax.swing.GroupLayout pnBuscarPedidoResultadoLayout = new javax.swing.GroupLayout(pnBuscarPedidoResultado);
        pnBuscarPedidoResultado.setLayout(pnBuscarPedidoResultadoLayout);
        pnBuscarPedidoResultadoLayout.setHorizontalGroup(
            pnBuscarPedidoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPedidoResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnBuscarPedidoResultadoLayout.setVerticalGroup(
            pnBuscarPedidoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPedidoResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnBuscarPessoaLayout = new javax.swing.GroupLayout(pnBuscarPessoa);
        pnBuscarPessoa.setLayout(pnBuscarPessoaLayout);
        pnBuscarPessoaLayout.setHorizontalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnBuscarPedidoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBuscarPedidoFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        pnBuscarPessoaLayout.setVerticalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPedidoFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBuscarPedidoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBuscarPedidoSelecionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarPedidoSelecionar.setText("Selecionar");
        btBuscarPedidoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPedidoSelecionarActionPerformed(evt);
            }
        });

        btBuscarPedidoLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarPedidoLimpar.setText("Limpar");
        btBuscarPedidoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPedidoLimparActionPerformed(evt);
            }
        });

        btBuscarPedidoSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarPedidoSair.setText("Sair");
        btBuscarPedidoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPedidoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btBuscarPedidoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarPedidoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarPedidoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscarPedidoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPedidoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPedidoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarPedidoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarPedidoPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPedidoPessoaActionPerformed

    private void tfBuscarPedidoPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarPedidoPessoaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPedidoPessoaKeyTyped

    private void btBuscarPedidoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPedidoLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btBuscarPedidoLimparActionPerformed

    private void btBuscarPedidoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPedidoSairActionPerformed
        // TODO add your handling code here:
        limparCampos();
        dispose();
    }//GEN-LAST:event_btBuscarPedidoSairActionPerformed

    private void btBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPedidoActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter dataFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String campoDataInicio = ffBuscarPedidoDataInicio.getText().trim();
        String campoDataFim = ffBuscarPedidoDataFim.getText().trim();
        LocalDate dataInicio;
        if (campoDataInicio.contains(" ") || campoDataInicio.equals("//")) {
            dataInicio = null;
        } else {
            dataInicio = LocalDate.parse(campoDataInicio, dataFormat);
        }
        LocalDate dataFim;
        if (campoDataFim.contains(" ") || campoDataFim.equals("//")) {
            dataFim = null;
        } else {
            dataFim = LocalDate.parse(campoDataFim, dataFormat);
        }
        try {
            pedidos = pedidoController.listarPedidos(tfBuscarPedidoPessoa.getText(), String.valueOf(cbBuscarPedidoTipoPessoa.getSelectedItem()), dataInicio, dataFim);
            alimentaTabela(pedidos);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btBuscarPedidoActionPerformed

    private void btBuscarPedidoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPedidoSelecionarActionPerformed
        // TODO add your handling code here:
        if (tableBuscarPessoa.getSelectedRow() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um pedido!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Pedido pedido = pedidoController.buscarPedidoPorId(pedidos.get(tableBuscarPessoa.getSelectedRow()).getId());
            tela.preenchePedido(pedido);
        } catch (Exception e) {
            e.printStackTrace();
        }
        limparCampos();
        dispose();
    }//GEN-LAST:event_btBuscarPedidoSelecionarActionPerformed
    
    public void alimentaTabela(List<Pedido> listagem) {
        modelo.setRowCount(0);
        for (Pedido pedido : listagem) {
            Object[] linha = {pedido.getId(), pedido.getCliente().getNome(), pedido.getCliente().getTipoUsuario(), pedido.getDataPedido()};
            modelo.addRow(linha);
        }
    }
    
    public void limparCampos() {
        tfBuscarPedidoPessoa.setText("");
        cbBuscarPedidoTipoPessoa.setSelectedIndex(0);
        ffBuscarPedidoDataInicio.setText("");
        ffBuscarPedidoDataFim.setText("");
        modelo.setRowCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarPedido;
    private javax.swing.JButton btBuscarPedidoLimpar;
    private javax.swing.JButton btBuscarPedidoSair;
    private javax.swing.JButton btBuscarPedidoSelecionar;
    private javax.swing.JComboBox<String> cbBuscarPedidoTipoPessoa;
    private javax.swing.JFormattedTextField ffBuscarPedidoDataFim;
    private javax.swing.JFormattedTextField ffBuscarPedidoDataInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarPedidoData1;
    private javax.swing.JLabel lbBuscarPedidoData2;
    private javax.swing.JLabel lbBuscarPedidoPessoa;
    private javax.swing.JLabel lbBuscarPedidoTipoPessoa;
    private javax.swing.JPanel pnBuscarPedidoFiltros;
    private javax.swing.JPanel pnBuscarPedidoResultado;
    private javax.swing.JPanel pnBuscarPessoa;
    private javax.swing.JTable tableBuscarPessoa;
    private javax.swing.JTextField tfBuscarPedidoPessoa;
    // End of variables declaration//GEN-END:variables
}
