/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.sistemanossolar.view;

import br.edu.iftm.sistemanossolar.controller.doacao.ProdutoController;
import br.edu.iftm.sistemanossolar.model.doacao.Produto;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AFSOUZA
 */
public class BuscarProduto extends javax.swing.JDialog {
    private static Telas tela;
    private static ProdutoController produtoController;
    private Produto produto;
    private static CadastroProduto cadastroProduto;
    private List<Produto> produtos;
    private DefaultTableModel modelo;
    /**
     * Creates new form BuscarPessoa
     */
    public BuscarProduto(java.awt.Frame parent, boolean modal, Connection conexao, Telas tela) {
        super(parent, modal);
        this.tela = tela;
        produtoController = new ProdutoController(conexao);
        cadastroProduto = new CadastroProduto(parent, true, conexao, tela);
        initComponents();
        modelo = (DefaultTableModel) tableBuscarPessoa.getModel();
        modelo.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBuscarPessoa = new javax.swing.JPanel();
        pnBuscarProdutoFiltros = new javax.swing.JPanel();
        lbBuscarProdutoNome = new javax.swing.JLabel();
        tfBuscarProdutoNome = new javax.swing.JTextField();
        lbBuscarProdutoTipo = new javax.swing.JLabel();
        cbBuscarProdutoTipo = new javax.swing.JComboBox<>();
        btBuscarDoacao = new javax.swing.JButton();
        pnBuscarProdutosResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscarPessoa = new javax.swing.JTable();
        btBuscarProdutoSelecionar = new javax.swing.JButton();
        btBuscarProdutoNovo = new javax.swing.JButton();
        btBuscarProdutoLimpar = new javax.swing.JButton();
        btBuscarProdutoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnBuscarPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        pnBuscarProdutoFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lbBuscarProdutoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbBuscarProdutoNome.setText("Produto:");

        tfBuscarProdutoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBuscarProdutoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarProdutoNomeActionPerformed(evt);
            }
        });
        tfBuscarProdutoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarProdutoNomeKeyTyped(evt);
            }
        });

        lbBuscarProdutoTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbBuscarProdutoTipo.setText("Tipo:");
        lbBuscarProdutoTipo.setToolTipText("");

        cbBuscarProdutoTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbBuscarProdutoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Alimento", "Limpeza", "Outro" }));

        btBuscarDoacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        btBuscarDoacao.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btBuscarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarDoacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarProdutoFiltrosLayout = new javax.swing.GroupLayout(pnBuscarProdutoFiltros);
        pnBuscarProdutoFiltros.setLayout(pnBuscarProdutoFiltrosLayout);
        pnBuscarProdutoFiltrosLayout.setHorizontalGroup(
            pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarProdutoFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarProdutoNome)
                    .addComponent(tfBuscarProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarProdutoFiltrosLayout.createSequentialGroup()
                        .addComponent(cbBuscarProdutoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscarDoacao))
                    .addComponent(lbBuscarProdutoTipo))
                .addContainerGap())
        );
        pnBuscarProdutoFiltrosLayout.setVerticalGroup(
            pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarProdutoFiltrosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarProdutoNome)
                    .addComponent(lbBuscarProdutoTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfBuscarProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbBuscarProdutoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btBuscarDoacao))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnBuscarProdutosResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tableBuscarPessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableBuscarPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cód.", "Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBuscarPessoa);

        javax.swing.GroupLayout pnBuscarProdutosResultadoLayout = new javax.swing.GroupLayout(pnBuscarProdutosResultado);
        pnBuscarProdutosResultado.setLayout(pnBuscarProdutosResultadoLayout);
        pnBuscarProdutosResultadoLayout.setHorizontalGroup(
            pnBuscarProdutosResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarProdutosResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnBuscarProdutosResultadoLayout.setVerticalGroup(
            pnBuscarProdutosResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarProdutosResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnBuscarPessoaLayout = new javax.swing.GroupLayout(pnBuscarPessoa);
        pnBuscarPessoa.setLayout(pnBuscarPessoaLayout);
        pnBuscarPessoaLayout.setHorizontalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnBuscarProdutosResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBuscarProdutoFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        pnBuscarPessoaLayout.setVerticalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarProdutoFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBuscarProdutosResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBuscarProdutoSelecionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarProdutoSelecionar.setText("Selecionar");
        btBuscarProdutoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProdutoSelecionarActionPerformed(evt);
            }
        });

        btBuscarProdutoNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarProdutoNovo.setText("Novo");
        btBuscarProdutoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProdutoNovoActionPerformed(evt);
            }
        });

        btBuscarProdutoLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarProdutoLimpar.setText("Limpar");
        btBuscarProdutoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProdutoLimparActionPerformed(evt);
            }
        });

        btBuscarProdutoSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscarProdutoSair.setText("Sair");
        btBuscarProdutoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProdutoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btBuscarProdutoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarProdutoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarProdutoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarProdutoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscarProdutoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarProdutoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarProdutoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarProdutoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarProdutoNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarProdutoNomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarProdutoNomeKeyTyped

    private void tfBuscarProdutoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarProdutoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarProdutoNomeActionPerformed

    private void btBuscarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProdutoBuscarActionPerformed
        String descricao = tfBuscarProdutoNome.getText();
        String tipo = (String) cbBuscarProdutoTipo.getSelectedItem();
        modelo.setRowCount(0);
        try {
            produtos = produtoController.listarProdutos(descricao, tipo);
            for(Produto produto : produtos){
                Object[] linha = {produto.getId(), produto.getNome()};
                modelo.addRow(linha);
            }
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_btBuscarProdutoBuscarActionPerformed

    public void limparTela() {
        tfBuscarProdutoNome.setText("");
        cbBuscarProdutoTipo.setSelectedIndex(0);
        modelo.setRowCount(0);
    }
    
    private void btBuscarProdutoLimparActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        limparTela();
    }

    private void btBuscarProdutoSairActionPerformed(java.awt.event.ActionEvent evt) {
        limparTela();
        dispose();
    }                                                   
    
    private void btBuscarProdutoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProdutoNovoActionPerformed
        cadastroProduto.setLocationRelativeTo(this);
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_btBuscarProdutoNovoActionPerformed

    private void btBuscarProdutoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProdutoSelecionarActionPerformed
        int indice = tableBuscarPessoa.getSelectedRow();
        if (tableBuscarPessoa.getSelectedRow() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um produto!", "Busca Produto", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            produto = produtos.get(indice);
            tela.preencheProdutoDoacao(produto);
            limparTela();
            dispose();
        }
    }//GEN-LAST:event_btBuscarProdutoSelecionarActionPerformed
    
    public Produto getProduto(){
        return produto;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarDoacao;
    private javax.swing.JButton btBuscarProdutoLimpar;
    private javax.swing.JButton btBuscarProdutoNovo;
    private javax.swing.JButton btBuscarProdutoSair;
    private javax.swing.JButton btBuscarProdutoSelecionar;
    private javax.swing.JComboBox<String> cbBuscarProdutoTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarProdutoNome;
    private javax.swing.JLabel lbBuscarProdutoTipo;
    private javax.swing.JPanel pnBuscarPessoa;
    private javax.swing.JPanel pnBuscarProdutoFiltros;
    private javax.swing.JPanel pnBuscarProdutosResultado;
    private javax.swing.JTable tableBuscarPessoa;
    private javax.swing.JTextField tfBuscarProdutoNome;
    // End of variables declaration//GEN-END:variables
}
