/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.sistemanossolar.view;

/**
 *
 * @author AFSOUZA
 */
public class BuscarPedido extends javax.swing.JDialog {

    /**
     * Creates new form BuscarPessoa
     */
    public BuscarPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBuscarPessoa = new javax.swing.JPanel();
        pnBuscarPedidoFiltros = new javax.swing.JPanel();
        lbBuscarPedidoPessoa = new javax.swing.JLabel();
        tfBuscarPedidoPessoa = new javax.swing.JTextField();
        lbBuscarPedidoTipoPessoa = new javax.swing.JLabel();
        cbBuscarPedidoTipoPessoa = new javax.swing.JComboBox<>();
        lbBuscarPedidoData1 = new javax.swing.JLabel();
        tfBuscarPedidoData1 = new javax.swing.JTextField();
        lbBuscarPedidoData2 = new javax.swing.JLabel();
        tfBuscarPedidoData2 = new javax.swing.JTextField();
        btBuscarPedidoBuscar = new javax.swing.JButton();
        pnBuscarPedidoResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscarPessoa = new javax.swing.JTable();
        btBuscarPedidoSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnBuscarPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Pedido"));

        pnBuscarPedidoFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        lbBuscarPedidoPessoa.setText("Nome da Pessoa");
        lbBuscarPedidoPessoa.setToolTipText("");

        tfBuscarPedidoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarPedidoPessoaActionPerformed(evt);
            }
        });
        tfBuscarPedidoPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarPedidoPessoaKeyTyped(evt);
            }
        });

        lbBuscarPedidoTipoPessoa.setText("Tipo");
        lbBuscarPedidoTipoPessoa.setToolTipText("");

        cbBuscarPedidoTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Assistente", "Beneficiário" }));

        lbBuscarPedidoData1.setText("Data Pedido Inicio");
        lbBuscarPedidoData1.setToolTipText("");

        tfBuscarPedidoData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarPedidoData1ActionPerformed(evt);
            }
        });
        tfBuscarPedidoData1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarPedidoData1KeyTyped(evt);
            }
        });

        lbBuscarPedidoData2.setText("Data Pedido Fim");
        lbBuscarPedidoData2.setToolTipText("");

        tfBuscarPedidoData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarPedidoData2ActionPerformed(evt);
            }
        });
        tfBuscarPedidoData2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarPedidoData2KeyTyped(evt);
            }
        });

        btBuscarPedidoBuscar.setText("Buscar");
        btBuscarPedidoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPedidoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarPedidoFiltrosLayout = new javax.swing.GroupLayout(pnBuscarPedidoFiltros);
        pnBuscarPedidoFiltros.setLayout(pnBuscarPedidoFiltrosLayout);
        pnBuscarPedidoFiltrosLayout.setHorizontalGroup(
            pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBuscarPedidoPessoa)
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPedidoPessoa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarPedidoTipoPessoa)
                    .addComponent(cbBuscarPedidoTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarPedidoData1)
                    .addComponent(tfBuscarPedidoData1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBuscarPedidoData2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBuscarPedidoData2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarPedidoBuscar)
                .addContainerGap())
        );
        pnBuscarPedidoFiltrosLayout.setVerticalGroup(
            pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPedidoPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBuscarPedidoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfBuscarPedidoData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPedidoData2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBuscarPedidoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBuscarPedidoData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscarPedidoBuscar)))
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPedidoTipoPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBuscarPedidoTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBuscarPedidoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarPedidoData1)
                        .addGap(26, 26, 26)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnBuscarPedidoResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        tableBuscarPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód.", "Pessoa", "Tipo", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBuscarPessoa);

        javax.swing.GroupLayout pnBuscarPedidoResultadoLayout = new javax.swing.GroupLayout(pnBuscarPedidoResultado);
        pnBuscarPedidoResultado.setLayout(pnBuscarPedidoResultadoLayout);
        pnBuscarPedidoResultadoLayout.setHorizontalGroup(
            pnBuscarPedidoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPedidoResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnBuscarPedidoResultadoLayout.setVerticalGroup(
            pnBuscarPedidoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPedidoResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        btBuscarPedidoSelecionar.setText("Selecionar");

        javax.swing.GroupLayout pnBuscarPessoaLayout = new javax.swing.GroupLayout(pnBuscarPessoa);
        pnBuscarPessoa.setLayout(pnBuscarPessoaLayout);
        pnBuscarPessoaLayout.setHorizontalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                        .addComponent(btBuscarPedidoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                        .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnBuscarPedidoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnBuscarPedidoFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        pnBuscarPessoaLayout.setVerticalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPedidoFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBuscarPedidoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuscarPedidoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarPedidoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPedidoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarPedidoBuscarActionPerformed

    private void tfBuscarPedidoData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarPedidoData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPedidoData1ActionPerformed

    private void tfBuscarPedidoData1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarPedidoData1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPedidoData1KeyTyped

    private void tfBuscarPedidoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarPedidoPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPedidoPessoaActionPerformed

    private void tfBuscarPedidoPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarPedidoPessoaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPedidoPessoaKeyTyped

    private void tfBuscarPedidoData2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarPedidoData2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPedidoData2KeyTyped

    private void tfBuscarPedidoData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarPedidoData2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarPedidoData2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarPedido dialog = new BuscarPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarPedidoBuscar;
    private javax.swing.JButton btBuscarPedidoSelecionar;
    private javax.swing.JComboBox<String> cbBuscarPedidoTipoPessoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarPedidoData1;
    private javax.swing.JLabel lbBuscarPedidoData2;
    private javax.swing.JLabel lbBuscarPedidoPessoa;
    private javax.swing.JLabel lbBuscarPedidoTipoPessoa;
    private javax.swing.JPanel pnBuscarPedidoFiltros;
    private javax.swing.JPanel pnBuscarPedidoResultado;
    private javax.swing.JPanel pnBuscarPessoa;
    private javax.swing.JTable tableBuscarPessoa;
    private javax.swing.JTextField tfBuscarPedidoData1;
    private javax.swing.JTextField tfBuscarPedidoData2;
    private javax.swing.JTextField tfBuscarPedidoPessoa;
    // End of variables declaration//GEN-END:variables
}
