/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.sistemanossolar.view;

import br.edu.iftm.sistemanossolar.controller.doacao.ProdutoController;
import br.edu.iftm.sistemanossolar.model.doacao.Produto;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AFSOUZA
 */
public class BuscarProduto extends javax.swing.JDialog {
    private static Telas tela;
    private static ProdutoController produtoController;
    private Produto produto;
    private static CadastroProduto cadastroProduto;
    private List<Produto> produtos;
    private DefaultTableModel modelo;
    /**
     * Creates new form BuscarPessoa
     */
    public BuscarProduto(java.awt.Frame parent, boolean modal, Connection conexao, Telas tela) {
        super(parent, modal);
        this.tela = tela;
        produtoController = new ProdutoController(conexao);
        cadastroProduto = new CadastroProduto(parent, true, conexao, tela);
        initComponents();
        modelo = (DefaultTableModel) tableBuscarPessoa.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBuscarPessoa = new javax.swing.JPanel();
        pnBuscarProdutoFiltros = new javax.swing.JPanel();
        lbBuscarProdutoNome = new javax.swing.JLabel();
        tfBuscarProdutoNome = new javax.swing.JTextField();
        lbBuscarProdutoTipo = new javax.swing.JLabel();
        cbBuscarProdutoTipo = new javax.swing.JComboBox<>();
        btBuscarProdutoBuscar = new javax.swing.JButton();
        pnBuscarProdutosResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscarPessoa = new javax.swing.JTable();
        btBuscarProdutoSelecionar = new javax.swing.JButton();
        btBuscarProdutoNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnBuscarPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Produto"));

        pnBuscarProdutoFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        lbBuscarProdutoNome.setText("Descrição");

        tfBuscarProdutoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarProdutoNomeActionPerformed(evt);
            }
        });
        tfBuscarProdutoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarProdutoNomeKeyTyped(evt);
            }
        });

        lbBuscarProdutoTipo.setText("Tipo");
        lbBuscarProdutoTipo.setToolTipText("");

        cbBuscarProdutoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Alimento", "Limpeza", "Outro" }));

        btBuscarProdutoBuscar.setText("Buscar");
        btBuscarProdutoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProdutoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarProdutoFiltrosLayout = new javax.swing.GroupLayout(pnBuscarProdutoFiltros);
        pnBuscarProdutoFiltros.setLayout(pnBuscarProdutoFiltrosLayout);
        pnBuscarProdutoFiltrosLayout.setHorizontalGroup(
            pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarProdutoFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarProdutoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarProdutoNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfBuscarProdutoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarProdutoTipo)
                    .addComponent(cbBuscarProdutoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarProdutoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnBuscarProdutoFiltrosLayout.setVerticalGroup(
            pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarProdutoFiltrosLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnBuscarProdutoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnBuscarProdutoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarProdutoNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBuscarProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBuscarProdutoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarProdutoTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBuscarProdutoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btBuscarProdutoBuscar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnBuscarProdutosResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        tableBuscarPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cód.", "Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBuscarPessoa);

        javax.swing.GroupLayout pnBuscarProdutosResultadoLayout = new javax.swing.GroupLayout(pnBuscarProdutosResultado);
        pnBuscarProdutosResultado.setLayout(pnBuscarProdutosResultadoLayout);
        pnBuscarProdutosResultadoLayout.setHorizontalGroup(
            pnBuscarProdutosResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarProdutosResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnBuscarProdutosResultadoLayout.setVerticalGroup(
            pnBuscarProdutosResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarProdutosResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        btBuscarProdutoSelecionar.setText("Selecionar");
        btBuscarProdutoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProdutoSelecionarActionPerformed(evt);
            }
        });

        btBuscarProdutoNovo.setText("Novo");
        btBuscarProdutoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProdutoNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarPessoaLayout = new javax.swing.GroupLayout(pnBuscarPessoa);
        pnBuscarPessoa.setLayout(pnBuscarPessoaLayout);
        pnBuscarPessoaLayout.setHorizontalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                        .addComponent(btBuscarProdutoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarProdutoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                        .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnBuscarProdutosResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnBuscarProdutoFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        pnBuscarPessoaLayout.setVerticalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarProdutoFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBuscarProdutosResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBuscarProdutoSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btBuscarProdutoNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarProdutoNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarProdutoNomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarProdutoNomeKeyTyped

    private void tfBuscarProdutoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarProdutoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarProdutoNomeActionPerformed

    private void btBuscarProdutoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProdutoBuscarActionPerformed
        String descricao = tfBuscarProdutoNome.getText();
        String tipo = (String) cbBuscarProdutoTipo.getSelectedItem();
        modelo.setRowCount(0);
        try {
            produtos = produtoController.listarProdutos(descricao, tipo);
            for(Produto produto : produtos){
                Object[] linha = {produto.getId(), produto.getNome()};
                modelo.addRow(linha);
            }
        } catch (SQLException ex) {
            
        }
        
        
    }//GEN-LAST:event_btBuscarProdutoBuscarActionPerformed

    private void btBuscarProdutoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProdutoNovoActionPerformed
        cadastroProduto.setLocationRelativeTo(this);
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_btBuscarProdutoNovoActionPerformed

    private void btBuscarProdutoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProdutoSelecionarActionPerformed
        int indice = tableBuscarPessoa.getSelectedRow();
        produto = produtos.get(indice);
        tela.preencheProdutoDoacao(produto);
        dispose();
    }//GEN-LAST:event_btBuscarProdutoSelecionarActionPerformed
    
    public Produto getProduto(){
        return produto;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarProdutoBuscar;
    private javax.swing.JButton btBuscarProdutoNovo;
    private javax.swing.JButton btBuscarProdutoSelecionar;
    private javax.swing.JComboBox<String> cbBuscarProdutoTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarProdutoNome;
    private javax.swing.JLabel lbBuscarProdutoTipo;
    private javax.swing.JPanel pnBuscarPessoa;
    private javax.swing.JPanel pnBuscarProdutoFiltros;
    private javax.swing.JPanel pnBuscarProdutosResultado;
    private javax.swing.JTable tableBuscarPessoa;
    private javax.swing.JTextField tfBuscarProdutoNome;
    // End of variables declaration//GEN-END:variables
}
