/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.sistemanossolar.view;

import java.sql.Connection;

/**
 *
 * @author AFSOUZA
 */
public class BuscarDoacao extends javax.swing.JDialog {
    private static Telas tela;
    /**
     * Creates new form BuscarPessoa
     */
    public BuscarDoacao(java.awt.Frame parent, boolean modal, Connection conexao, Telas tela) {
        super(parent, modal);
        initComponents();
        this.tela = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBuscarPessoa = new javax.swing.JPanel();
        pnBuscarDoacaoFiltros = new javax.swing.JPanel();
        lbBuscarDoacaoDoador = new javax.swing.JLabel();
        tfBuscarDoacaoDoador = new javax.swing.JTextField();
        lbBuscarDoacaoTipo = new javax.swing.JLabel();
        cbBuscarDocaoTipo = new javax.swing.JComboBox<>();
        lbBuscarDoacaoData1 = new javax.swing.JLabel();
        tfBuscarDoacaoData1 = new javax.swing.JTextField();
        lbBuscarDoacaoData2 = new javax.swing.JLabel();
        tfBuscarDoacao2 = new javax.swing.JTextField();
        btBuscarDoacao = new javax.swing.JButton();
        pnBuscarDoacaoResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscarPessoa = new javax.swing.JTable();
        btBuscarDoacaoSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnBuscarPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Doação"));

        pnBuscarDoacaoFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        lbBuscarDoacaoDoador.setText("Nome do Doador");
        lbBuscarDoacaoDoador.setToolTipText("");

        tfBuscarDoacaoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarDoacaoDoadorActionPerformed(evt);
            }
        });
        tfBuscarDoacaoDoador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarDoacaoDoadorKeyTyped(evt);
            }
        });

        lbBuscarDoacaoTipo.setText("Tipo");
        lbBuscarDoacaoTipo.setToolTipText("");

        cbBuscarDocaoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Dinheiro", "Produto" }));

        lbBuscarDoacaoData1.setText("Data Inicio");
        lbBuscarDoacaoData1.setToolTipText("");

        tfBuscarDoacaoData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarDoacaoData1ActionPerformed(evt);
            }
        });
        tfBuscarDoacaoData1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarDoacaoData1KeyTyped(evt);
            }
        });

        lbBuscarDoacaoData2.setText("Data Fim");
        lbBuscarDoacaoData2.setToolTipText("");

        tfBuscarDoacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarDoacao2ActionPerformed(evt);
            }
        });
        tfBuscarDoacao2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarDoacao2KeyTyped(evt);
            }
        });

        btBuscarDoacao.setText("Buscar");
        btBuscarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarDoacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBuscarDoacaoFiltrosLayout = new javax.swing.GroupLayout(pnBuscarDoacaoFiltros);
        pnBuscarDoacaoFiltros.setLayout(pnBuscarDoacaoFiltrosLayout);
        pnBuscarDoacaoFiltrosLayout.setHorizontalGroup(
            pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarDoacaoDoador)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfBuscarDoacaoDoador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarDoacaoTipo)
                    .addComponent(cbBuscarDocaoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarDoacaoData1)
                    .addComponent(tfBuscarDoacaoData1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarDoacaoData2)
                    .addComponent(tfBuscarDoacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarDoacao)
                .addContainerGap())
        );
        pnBuscarDoacaoFiltrosLayout.setVerticalGroup(
            pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfBuscarDoacaoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBuscarDoacaoData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarDoacaoData2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBuscarDoacao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btBuscarDoacao)
                    .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                        .addComponent(lbBuscarDoacaoTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBuscarDocaoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBuscarDoacaoFiltrosLayout.createSequentialGroup()
                        .addGroup(pnBuscarDoacaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbBuscarDoacaoDoador)
                            .addComponent(lbBuscarDoacaoData1))
                        .addGap(26, 26, 26)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnBuscarDoacaoResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        tableBuscarPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód.", "Tipo", "Doador", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBuscarPessoa);

        javax.swing.GroupLayout pnBuscarDoacaoResultadoLayout = new javax.swing.GroupLayout(pnBuscarDoacaoResultado);
        pnBuscarDoacaoResultado.setLayout(pnBuscarDoacaoResultadoLayout);
        pnBuscarDoacaoResultadoLayout.setHorizontalGroup(
            pnBuscarDoacaoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarDoacaoResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnBuscarDoacaoResultadoLayout.setVerticalGroup(
            pnBuscarDoacaoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarDoacaoResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        btBuscarDoacaoSelecionar.setText("Selecionar");

        javax.swing.GroupLayout pnBuscarPessoaLayout = new javax.swing.GroupLayout(pnBuscarPessoa);
        pnBuscarPessoa.setLayout(pnBuscarPessoaLayout);
        pnBuscarPessoaLayout.setHorizontalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                        .addComponent(btBuscarDoacaoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                        .addGroup(pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnBuscarDoacaoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnBuscarDoacaoFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        pnBuscarPessoaLayout.setVerticalGroup(
            pnBuscarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarDoacaoFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBuscarDoacaoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuscarDoacaoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBuscarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarDoacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarDoacaoActionPerformed

    private void tfBuscarDoacaoData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarDoacaoData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarDoacaoData1ActionPerformed

    private void tfBuscarDoacaoData1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarDoacaoData1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarDoacaoData1KeyTyped

    private void tfBuscarDoacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarDoacao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarDoacao2ActionPerformed

    private void tfBuscarDoacao2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarDoacao2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarDoacao2KeyTyped

    private void tfBuscarDoacaoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarDoacaoDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarDoacaoDoadorActionPerformed

    private void tfBuscarDoacaoDoadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarDoacaoDoadorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarDoacaoDoadorKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarDoacao;
    private javax.swing.JButton btBuscarDoacaoSelecionar;
    private javax.swing.JComboBox<String> cbBuscarDocaoTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarDoacaoData1;
    private javax.swing.JLabel lbBuscarDoacaoData2;
    private javax.swing.JLabel lbBuscarDoacaoDoador;
    private javax.swing.JLabel lbBuscarDoacaoTipo;
    private javax.swing.JPanel pnBuscarDoacaoFiltros;
    private javax.swing.JPanel pnBuscarDoacaoResultado;
    private javax.swing.JPanel pnBuscarPessoa;
    private javax.swing.JTable tableBuscarPessoa;
    private javax.swing.JTextField tfBuscarDoacao2;
    private javax.swing.JTextField tfBuscarDoacaoData1;
    private javax.swing.JTextField tfBuscarDoacaoDoador;
    // End of variables declaration//GEN-END:variables
}
