/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.sistemanossolar.view;

import java.sql.Connection;

import br.edu.iftm.sistemanossolar.controller.doacao.ProdutoController;

/**
 *
 * @author AFSOUZA
 */
public class CadastroProduto extends javax.swing.JDialog {
    private static Telas tela;
    private static ProdutoController produtoController;
    /**
     * Creates new form CadastroProduto1
     */
    public CadastroProduto(java.awt.Frame parent, boolean modal, Connection conexao, Telas tela) {
        super(parent, modal);
        produtoController = new ProdutoController(conexao);
        this.tela = tela;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCadastrarProduto = new javax.swing.JPanel();
        lbCadProdTipo = new javax.swing.JLabel();
        cbCadProdTipoProduto = new javax.swing.JComboBox<>();
        lbCadProdProduto = new javax.swing.JLabel();
        tfCadProdProduto = new javax.swing.JTextField();
        btCadProdCadastrar = new javax.swing.JButton();
        btCadProdCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnCadastrarProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Produto"));

        lbCadProdTipo.setText("Tipo de Produto");

        cbCadProdTipoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbCadProdProduto.setText("Produto");

        btCadProdCadastrar.setText("Cadastrar");

        btCadProdCancelar.setText("Cancelar");

        javax.swing.GroupLayout pnCadastrarProdutoLayout = new javax.swing.GroupLayout(pnCadastrarProduto);
        pnCadastrarProduto.setLayout(pnCadastrarProdutoLayout);
        pnCadastrarProdutoLayout.setHorizontalGroup(
            pnCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastrarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnCadastrarProdutoLayout.createSequentialGroup()
                        .addComponent(btCadProdCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btCadProdCadastrar))
                    .addGroup(pnCadastrarProdutoLayout.createSequentialGroup()
                        .addGroup(pnCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbCadProdTipo)
                            .addComponent(lbCadProdProduto)
                            .addComponent(cbCadProdTipoProduto, 0, 310, Short.MAX_VALUE)
                            .addComponent(tfCadProdProduto))
                        .addGap(36, 36, 36)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnCadastrarProdutoLayout.setVerticalGroup(
            pnCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastrarProdutoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbCadProdTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCadProdTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCadProdProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCadProdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(pnCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadProdCadastrar)
                    .addComponent(btCadProdCancelar))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadProdCadastrar;
    private javax.swing.JButton btCadProdCancelar;
    private javax.swing.JComboBox<String> cbCadProdTipoProduto;
    private javax.swing.JLabel lbCadProdProduto;
    private javax.swing.JLabel lbCadProdTipo;
    private javax.swing.JPanel pnCadastrarProduto;
    private javax.swing.JTextField tfCadProdProduto;
    // End of variables declaration//GEN-END:variables
}
